name: Build Go Cross Platform

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  artifact_name: mirai-val-bot

on:
  release:
    types:
      - created

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [ "amd64", "arm64", "arm" ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build Linux
        run: go build -o ./dist/${{ env.artifact_name }}-${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.artifact_name }}
          path: 'dist'

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build Windows
        run: go build --buildmode=exe -o ./dist/${{ env.artifact_name }}.exe

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.artifact_name }}
          path: 'dist'

  upload_release:
    runs-on: ubuntu-latest
    needs: [ build_windows, build_linux ]
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: ${{ env.artifact_name }}

      - name: zip the directory
        run: |
          [ -d ${{steps.download.outputs.download-path}} ] && ls -la ${{ steps.download.outputs.download-path }}
          cd ${{steps.download.outputs.download-path}}
          zip -r ${{ env.artifact_name }}.zip .
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3

      - name: Upload Release
        id: upload-release-zip
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${{ env.artifact_name }}.zip
          asset_name: ${{ env.artifact_name }}.zip
          asset_content_type: application/zip
